# INSTALAR O MODULO REQUESTS
# pip install requests

# IMPORTAR O MODULO INSTALADO 'REQUESTS'
import requests

# VARIAVEL TEXTO QUE IRÁ ARMAZENAR O CEP PARA SER CONSULTADO
# PROGRAMAR UMA ENTRADA DE DADOS PARA QUE O USUÁRIO POSSA INFORMAR O CEP
# QUE SERÁ CONSULTADO
# PARA ISSO UTILIZAREMOS O INPUT
cep = input("Informe o CEP para consulta: ")

print("CEP: ", cep)

# URL DEFINIDA PELA API
# PARA CONSULTAR O CEP É NECESSARIO INFORMAR NO FINAL DA URL
# ENTÃO PODEMOS CONCATENAR OU INTERPOLAR PARA EXECUTAR A CONSULTA
url = "https://cep.awesomeapi.com.br/json/" + cep

print("URl: ", url)

# EXECUTAR O COMANDO DE CONSULTA DE DADOS UTILIZANO O MÉTODO GET
# RETORNO DO CONTEUDO RETORNADO PELA API SERÁ ARMAZENADO NA VARIAVEL 'RETORNO_API'
retorno_api = requests.get(url)

print("RETORNO API: ", retorno_api)

# PEGAR O RESULTADO GERADO DENTRO DO "ARQUIVO" JSON E ARMAZENAR
# EM UMA VARAIVEL DO PYTHON, PARA ISSO É NECESSARIO TRANSFORMAR EM UMA ESTRUTURA DE COLEÇÃO
retorno_dados = retorno_api.json()

print("RETORNO DADOS: ", retorno_dados)

# ANALIZANDO OS DADOS QUE FORAM RETORNADOS, FOI ENTENDIDO QUE A CHAVE "ADDRESS" POSSUI O RESULTADO ESPERADO
endereco = retorno_dados["address"]

print("ENDEREÇO: ", endereco)
